version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

jobs:
  sonar-scanning:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install SonarScanner
          command: |
            curl -sSfL https://get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install sonar-scanner
      - run:
          name: Run SonarQube scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.sources=src \
              -Dsonar.host.url=https://your-sonarqube-instance.com \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - sonar-scanning
